In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns",350)
from datetime import datetime
from dateutil.relativedelta import relativedelta
import csv
from sklearn.preprocessing import LabelEncoder

In [2]:
# Import Train & Test

In [3]:
df_train = pd.read_csv('train.csv',sep=',')

In [4]:
df_test = pd.read_csv('test.csv',sep=',')

In [5]:
df_train.shape

(356669, 36)

In [6]:
df_test.shape

(79771, 35)

In [7]:
df_test.head()

echeance_annee  echeance_mois produit  duree        type_d_offre  \
0            2017              3    Elec     12      Grille de prix   
1            2017              6     Gaz     36  Prix individualisé   
2            2017              1     Gaz     36  Prix individualisé   
3            2017              8     Gaz     12  Prix individualisé   
4            2017              8     Gaz     12  Prix individualisé   

     type_de_prix    canal_de_vente       zone    marche_de_la_sc  \
0  GPRS Prix Fixe    Vente physique        NaN  RESIDENTIEL PRIVE   
1       Référence  Vente à distance   ZONE SUD          TERTIAIRE   
2       Référence  Vente à distance   ZONE SUD          TERTIAIRE   
3             NaN  Vente à distance  ZONE NORD          TERTIAIRE   
4             NaN    Vente physique       TIGF          TERTIAIRE   

  segment_societe_contractante                    entite_societe_contractante  \
0            Résidentiel privé             Entreprises & territoires Nord Est   
1              Tertiaire privé  Entreprises & territoires vente et multicanal   
2              Tertiaire privé  Entreprises & territoires vente et multicanal   
3              Tertiaire privé  Entreprises & territoires vente et multicanal   
4              Tertiaire privé          Entreprises & territoires Grand Ouest   

                  profil_prm couleur_tarif_elec  volume_annuel  prix_gaz_m3  \
0  BT < 36 - simple (Simple)               Bleu        0.11860    17.313520   
1                       P019                NaN        4.96180    16.783495   
2                       P019                NaN        4.96180    16.615879   
3                       P017                NaN        1.28400    16.614452   
4                       P019                NaN        3.78125    16.614452   

   prix_elec_m3  nb_dem_12  nb_recla_12  nb_dem_reco_12  nb_recla_reco_12  \
0     38.065238          0            0               0                 0   
1     34.830435          0            0               0                 0   
2     41.947143          2            0               1                 0   
3     35.679091          0            0               0                 0   
4     35.679091          0            0               0                 0   

  type_client                                        libelle_naf  \
0        dual  Administration d'immeubles et autres biens imm...   
1         NaN                                                NaN   
2         NaN                                                NaN   
3         NaN                                                NaN   
4         gaz                    Enseignement secondaire général   

                                        activite_nce  anciennete_client  \
0  Services marchands divers (hors santé et ensei...          13.964384   
1                                                NaN                NaN   
2                                                NaN                NaN   
3                                                NaN                NaN   
4                                       Enseignement          13.830137   

  orientation_economique  population  evolution_pop_percent  nb_proprietaire  \
0          Bassin Urbain      9751.0                   0.07           1693.0   
1          Bassin Urbain      5847.0                   0.05           1095.0   
2          Bassin Urbain      5847.0                   0.05           1095.0   
3          Bassin Urbain     73599.0                   0.06          13867.0   
4          Bassin Urbain    390301.0                   0.04          62541.0   

   nb_logement  dep_moyenne_salaires_horaires  urbanite_ruralite  nb_atifs  \
0       4574.0                      11.173529  Com > 200 m habts    3642.0   
1       1957.0                      12.399057   Com < 50 m habts    2242.0   
2       1957.0                      12.399057   Com < 50 m habts    2242.0   
3      32783.0                      17.731429  Com > 200 m habts   34285.0   
4    

In [8]:
df_train.head(5)

cible  echeance_annee  echeance_mois produit  duree        type_d_offre  \
0      1            2016              3    Elec     12      Grille de prix   
1      1            2014              3    Elec     12      Grille de prix   
2      1            2013              3    Elec     12      Grille de prix   
3      1            2015              3    Elec     12      Grille de prix   
4      1            2014              9     Gaz     12  Prix individualisé   

     type_de_prix  canal_de_vente       zone    marche_de_la_sc  \
0  GPRS Prix Fixe  Vente physique        NaN  RESIDENTIEL PRIVE   
1  GPRS Prix Fixe  Vente physique        NaN  RESIDENTIEL PRIVE   
2  GPRS Prix Fixe  Vente physique        NaN  RESIDENTIEL PRIVE   
3  GPRS Prix Fixe  Vente physique        NaN  RESIDENTIEL PRIVE   
4       Référence  Vente physique  ZONE NORD          TERTIAIRE   

  segment_societe_contractante         entite_societe_contractante  \
0            Résidentiel privé  Entreprises & territoires Nord Est   
1            Résidentiel privé  Entreprises & territoires Nord Est   
2            Résidentiel privé  Entreprises & territoires Nord Est   
3            Résidentiel privé  Entreprises & territoires Nord Est   
4              Tertiaire privé  Entreprises & territoires Nord Est   

                  profil_prm couleur_tarif_elec  volume_annuel  prix_gaz_m3  \
0  BT < 36 - simple (Simple)               Bleu        0.11860    16.415322   
1  BT < 36 - simple (Simple)               Bleu        0.11860    27.547958   
2  BT < 36 - simple (Simple)               Bleu        0.11860          NaN   
3  BT < 36 - simple (Simple)               Bleu        0.11860    22.850872   
4                       P017                NaN        5.50545    24.530851   

   prix_elec_m3  nb_dem_12  nb_recla_12  nb_dem_reco_12  nb_recla_reco_12  \
0     34.367000          0            0               0                 0   
1     43.686875          0            0               0                 0   
2           NaN          0            0               0                 0   
3     40.846316          0            0               0                 0   
4     41.823333          0            0               0                 0   

  type_client                                        libelle_naf  \
0        dual  Administration d'immeubles et autres biens imm...   
1        dual  Administration d'immeubles et autres biens imm...   
2        dual  Administration d'immeubles et autres biens imm...   
3        dual  Administration d'immeubles et autres biens imm...   
4         gaz           Entreposage et stockage non frigorifique   

                                        activite_nce  anciennete_client  \
0  Services marchands divers (hors santé et ensei...          13.964384   
1  Services marchands divers (hors santé et ensei...          13.964384   
2  Services marchands divers (hors santé et ensei...          13.964384   
3  Services marchands divers (hors santé et ensei...          13.964384   
4  Services marchands divers (hors santé et ensei...          14.920548   

  orientation_economique  population  evolution_pop_percent  nb_proprietaire  \
0          Bassin Urbain      9751.0                   0.07           1693.0   
1          Bassin Urbain      9751.0                   0.07           1693.0   
2          Bassin Urbain      9751.0                   0.07           1693.0   
3          Bassin Urbain      9751.0                   0.07           1693.0   
4      Bassin Industriel      1700.0                   0.06            430.0   

   nb_logement  dep_moyenne_salaires_horaires  urbanite_ruralite  nb_atifs  \
0       4574.0                      11.173529  Com > 200 m habts    3642.0   
1       4574.0                      11.173529  Com > 200 m habts    3642.0   
2       4574.0                      11.173529  Com > 200 m habts    3642.0   
3       4574.0                      11.173529  Com > 200 m habts    3642.0   
4        623.0                      11.98

In [9]:
df_train.columns

Index(['cible', 'echeance_annee', 'echeance_mois', 'produit', 'duree',
       'type_d_offre', 'type_de_prix', 'canal_de_vente', 'zone',
       'marche_de_la_sc', 'segment_societe_contractante',
       'entite_societe_contractante', 'profil_prm', 'couleur_tarif_elec',
       'volume_annuel', 'prix_gaz_m3', 'prix_elec_m3', 'nb_dem_12',
       'nb_recla_12', 'nb_dem_reco_12', 'nb_recla_reco_12', 'type_client',
       'libelle_naf', 'activite_nce', 'anciennete_client',
       'orientation_economique', 'population', 'evolution_pop_percent',
       'nb_proprietaire', 'nb_logement', 'dep_moyenne_salaires_horaires',
       'urbanite_ruralite', 'nb_atifs', 'dynamique_demographique_bv',
       'environnement_demographique', 'seg_dyn_entre'],
      dtype='object')

In [10]:
df_train.dtypes

cible                              int64
echeance_annee                     int64
echeance_mois                      int64
produit                           object
duree                              int64
type_d_offre                      object
type_de_prix                      object
canal_de_vente                    object
zone                              object
marche_de_la_sc                   object
segment_societe_contractante      object
entite_societe_contractante       object
profil_prm                        object
couleur_tarif_elec                object
volume_annuel                    float64
prix_gaz_m3                      float64
prix_elec_m3                     float64
nb_dem_12                          int64
nb_recla_12                        int64
nb_dem_reco_12                     int64
nb_recla_reco_12                   int64
type_client                       object
libelle_naf                       object
activite_nce                      object
anciennete_clien

In [11]:
df_train.isnull().sum()

cible                                 0
echeance_annee                        0
echeance_mois                         0
produit                               0
duree                                 0
type_d_offre                          0
type_de_prix                        568
canal_de_vente                        0
zone                             307510
marche_de_la_sc                       0
segment_societe_contractante          0
entite_societe_contractante           0
profil_prm                         7582
couleur_tarif_elec                54267
volume_annuel                     15276
prix_gaz_m3                       82005
prix_elec_m3                      16369
nb_dem_12                             0
nb_recla_12                           0
nb_dem_reco_12                        0
nb_recla_reco_12                      0
type_client                       68158
libelle_naf                       68384
activite_nce                      68397
anciennete_client                 68158


In [12]:
df_train.echeance_annee.unique()

array([2016, 2014, 2013, 2015], dtype=int64)

In [13]:
df_train.echeance_mois.unique()

array([ 3,  9,  4,  6,  8, 10, 12,  1,  7, 11,  2,  5], dtype=int64)

In [14]:
df_train.produit.unique()

array(['Elec', 'Gaz'], dtype=object)

In [15]:
df_train.duree.unique()

array([12, 36,  0, 24, 60,  5, 48, 11, 25, 13, 16,  3, 22, 14,  7, 10,  1,
       20, 28,  6, 33,  4, 18,  8, 38], dtype=int64)

In [16]:
df_train.type_d_offre.unique()

array(['Grille de prix', 'Prix individualisé'], dtype=object)

In [17]:
df_train.type_de_prix.unique()

array(['GPRS Prix Fixe', 'Référence', nan, 'Connecté marché', 'Prix Fixe',
       "MAITRIZ' 100% fixe", 'Offre de bascule', 'Indexé Marché',
       'Prix Fixe garanti', 'Grille de prix indexé TR',
       'Grille de prix fixe', "MAITRIZ' énergie fixe", 'Reflet Marché',
       'Grille de prix FT', "ORIGIN'"], dtype=object)

In [18]:
df_train.canal_de_vente.unique()

array(['Vente physique', 'Vente à distance'], dtype=object)

In [19]:
df_train.zone.unique()

array([nan, 'ZONE NORD', 'ZONE SUD', 'TIGF'], dtype=object)

In [20]:
df_train.marche_de_la_sc.unique()

array(['RESIDENTIEL PRIVE', 'TERTIAIRE', 'INDUSTRIE'], dtype=object)

In [21]:
df_train.segment_societe_contractante.unique()

array(['Résidentiel privé', 'Tertiaire privé', 'Industrie',
       'OP Energétique'], dtype=object)

In [22]:
df_train.entite_societe_contractante.unique()

array(['Entreprises & territoires Nord Est',
       'Entreprises & territoires vente et multicanal',
       'Entreprises & territoires IDF',
       'Entreprises & territoires Grand Ouest',
       'Entreprises & territoires Sud Est'], dtype=object)

In [23]:
df_train.profil_prm.unique()

array(['BT < 36 - simple (Simple)', 'P017', nan, 'P019',
       'BT > 36 -4 index', 'P016', 'P015', 'P014', 'P018', 'P013', 'P012',
       'P011', 'BT < 36- double (HP HC)', 'BT < 36 - EP (Simple EP)',
       'BT < 36 -4index', 'HTA5 (5 index)'], dtype=object)

In [24]:
df_train.couleur_tarif_elec.unique()

array(['Bleu', nan, 'Jaune', 'Vert'], dtype=object)

In [25]:
df_train.volume_annuel.unique()

array([ 0.1186 ,  5.50545,  2.15   , ...,  0.4533 ,  0.5113 ,  2.89705])

In [26]:
df_train.prix_gaz_m3.unique()

array([ 16.41532179,  27.54795777,          nan,  22.85087161,
        24.53085071,  21.73395267,  26.4850501 ,  25.2855065 ,
        24.82315031,  21.8973861 ,  16.52716421,  24.4574753 ,
        25.26055559,  22.13723742,  18.51949083,  24.24378953,
        26.57648137,  22.09783301,  13.94988167,  24.75644133,
        20.60054182,  15.12237223,  20.02613546,  15.23112229,
        26.69965096,  17.62325459,  23.71098401,  25.1518473 ,
        13.84534736,  21.38557731,  27.05092818,  15.7407481 ,
        22.59176055,  16.81678376,  14.68604821,  14.19362677,
        19.40147345,  25.80665473])

In [27]:
df_train.prix_elec_m3.unique()

array([ 34.367     ,  43.686875  ,          nan,  40.84631579,
        41.82333333,  38.57863636,  41.87789474,  46.18318182,
        42.70818182,  42.90095238,  44.3235    ,  42.1       ,
        41.92      ,  38.62105263,  41.94869565,  32.67227273,
        41.94391304,  43.05136364,  38.86272727,  36.99      ,
        43.0273913 ,  43.03      ,  39.0695    ,  28.29857143,
        43.68904762,  42.0825    ,  38.01428571,  30.05727273,
        39.05428571,  33.53272727,  43.11761905,  36.3652381 ,
        42.5185    ,  42.8247619 ,  41.90714286,  26.02285714,
        39.60565217,  42.7855    ,  31.98      ,  39.8925    ,
        33.23238095,  29.9785    ,  26.7252381 ,  38.01727273,
        42.9575    ,  45.1415    ])

In [28]:
df_train.nb_dem_12.unique()

array([ 0,  1,  2,  5,  4,  3,  7,  6,  8, 10,  9, 12, 11, 15, 13, 17, 16], dtype=int64)

In [29]:
df_train.nb_recla_12.unique()

array([0, 1, 2, 4, 3, 6, 5, 7, 8, 9], dtype=int64)

In [30]:
df_train.nb_dem_reco_12.unique()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [31]:
df_train.nb_recla_reco_12.unique()

array([0, 1, 2, 4, 3], dtype=int64)

In [32]:
df_train.type_client.unique()

array(['dual', 'gaz', nan, 'élec'], dtype=object)

In [33]:
df_train.libelle_naf.unique()

array(["Administration d'immeubles et autres biens immobiliers",
       'Entreposage et stockage non frigorifique', nan,
       'Enseignement secondaire technique ou professionnel',
       'Hébergement médicalisés pour enfants handicapés',
       'Commerce de voitures et de véhicules automobiles légers',
       'Agences immobilières', 'Hôtels et hébergement similaire',
       'Enseignement secondaire général',
       'Commerce de détail de produits pharmaceutiques en magasin sp',
       'Activités des organisations religieuses', 'Autres hébergements',
       "Commerce de gros (commerce interentreprises) d'ordinateurs,",
       'Fabrication de tubes, tuyaux, profilés creux et accessoires',
       'Commerce de gros (commerce interentreprises) de fournitures',
       "Fabrication d'articles textiles, sauf habillement",
       'Fonderie de métaux légers',
       'Hébergement social pour handicapés mentaux et malades mentau',
       'Aide par le travail',
       'Hébergement médicalisé pour

In [34]:
df_train.activite_nce.unique()

array(['Services marchands divers (hors santé et enseignement)', nan,
       'Enseignement', 'Santé', 'Commerce', 'Hébergement et restauration',
       'Administrations et services non marchands',
       'Fonderie, travail des métaux et première transformation de l',
       "Industrie textile, du cuir et de l'habillement",
       'Industries diverses',
       "Construction de véhicules automobiles et d'autres matériels",
       'Industries alimentaires, hors industrie du lait et du sucre',
       'Construction mécanique',
       'Transports routiers, urbains, par conduite',
       'Bâtiment et génie civil', 'Agriculture, sylviculture',
       'Fabrication de produits en plastique',
       'Parachimie et industrie pharmaceutique',
       'Construction navale et aéronautique,armement',
       'Autres industries de la chimie organique de base',
       'Construction électrique et électronique',
       'Télécommunications et postes', 'Chauffage urbain',
       'Industrie du papier et du car

In [35]:
df_train.anciennete_client.unique()

array([ 13.96438356,  14.92054795,          nan, ...,   1.83835616,
         1.66575342,   1.63561644])

In [36]:
df_train.orientation_economique.unique()

array(['Bassin Urbain', 'Bassin Industriel', 'Bassin Résidentiel',
       'Bassins Agroalimentaire', nan, 'Bassin diversifié'], dtype=object)

In [37]:
df_train.population.unique()

array([ 9751.,  1700.,  2912., ...,   585.,    51.,  1684.])

In [38]:
df_train.evolution_pop_percent.unique()

array([ 0.07,  0.06,  0.02,  0.05,  0.03,  0.04,  0.  , -0.1 ,  0.09,
       -0.02, -0.03,   nan,  0.12,  0.14,  0.08,  0.11, -0.01,  0.01,
       -0.07,  0.13, -0.06, -0.05, -0.04,  0.1 , -0.17, -0.09, -0.08,
       -0.14,  0.15,  0.17, -0.23, -0.11, -0.2 , -0.27, -0.18,  0.16,
       -0.13, -0.12, -0.25, -0.16, -0.15])

In [39]:
df_train.nb_proprietaire.unique()

array([ 1693.,   430.,   852., ...,   104.,   252.,    16.])

In [40]:
df_train.nb_logement.unique()

array([ 4574.,   623.,  1222., ...,  1741.,  1122.,    40.])

In [41]:
df_train.dep_moyenne_salaires_horaires.unique()

array([ 11.17352941,  11.98142857,  11.42      ,  17.058     ,
        10.565     ,  10.70827586,  17.8       ,  10.95526316,
        12.3990566 ,  10.91868132,  14.44574468,  11.43409091,
        13.08547009,  10.43333333,  11.2047619 ,  17.73142857,
        11.03214286,  10.93636364,          nan,  11.05925926,
        14.1787234 ,  10.4       ,  10.32903226,  12.77692308,
        11.67959184,  13.71052632,  11.21594828,  12.47789474,
        10.63589744,  13.19038462,  10.67096774,  10.48095238,
        11.06885246,  10.51764706,  11.21168831,  10.81386139,
        11.32121212,  10.2       ,  11.52068966,  10.39375   ,
        11.76625   ,  10.23      ,  11.73950617,  11.59142857,
        10.00441176,  10.55571429,  11.4255814 ,  11.54747475,
        11.40441176,  11.0075    ,  10.08461538,  10.77794118,
        10.25714286,  10.22608696,  11.7725    ,  10.11578947,
        10.63333333,  10.85869565,  11.55416667,  10.98695652,
        10.7       ,  10.365     ,  10.44358974,  10.96

In [42]:
df_train.urbanite_ruralite.unique()

array(['Com > 200 m habts', 'Com < 10 m habts', 'Com < 50 m habts',
       'Com < 200 m habts', 'Com rurale < 2 000 m habts', nan,
       'Com rurale > 2 000 habts'], dtype=object)

In [43]:
df_train.nb_atifs.unique()

array([ 3642.,   745.,  1413., ...,   262.,  1801.,    25.])

In [44]:
df_train.dynamique_demographique_bv.unique()

array(['Grande Ville',
       '1.Accroissement par excédent naturel et migratoire',
       '3.Accroissement par excédent migratoire', nan,
       '6.Déclin par déficit migratoire',
       '2.Accroissement par excédent naturel',
       '4.Déclin par déficit naturel et migratoire',
       '5.Déclin par déficit naturel'], dtype=object)

In [45]:
df_train.environnement_demographique.unique()

array(['Bassin Urbain en croissance démographique',
       'Bassin Industriel en croissance démographique',
       'Bassin Résidentiel en croissance démographique',
       'Bassins Agroalimentaire en croissance démographique', nan,
       'Bassin diversifié en croissance démographique'], dtype=object)

In [46]:
df_train.seg_dyn_entre.unique()

array(['Dynamique Economique', 'Faible dynamique', nan, 'Moyenne dynamique'], dtype=object)

In [47]:
df_train.describe(include=[np.object, pd.Categorical]).T

count unique  \
produit                       356669      2   
type_d_offre                  356669      2   
type_de_prix                  356101     14   
canal_de_vente                356669      2   
zone                           49159      3   
marche_de_la_sc               356669      3   
segment_societe_contractante  356669      4   
entite_societe_contractante   356669      5   
profil_prm                    349087     15   
couleur_tarif_elec            302402      3   
type_client                   288511      3   
libelle_naf                   288285    523   
activite_nce                  288272     38   
orientation_economique        275147      5   
urbanite_ruralite             275147      6   
dynamique_demographique_bv    275147      7   
environnement_demographique   275147      5   
seg_dyn_entre                 275147      3   

                                                                            top  \
produit                                                                    Elec   
type_d_offre                                                     Grille de prix   
type_de_prix                                                 MAITRIZ' 100% fixe   
canal_de_vente                                                   Vente physique   
zone                                                                  ZONE NORD   
marche_de_la_sc                                               RESIDENTIEL PRIVE   
segment_societe_contractante                                  Résidentiel privé   
entite_societe_contractante       Entreprises & territoires vente et multicanal   
profil_prm                                            BT < 36 - simple (Simple)   
couleur_tarif_elec                                                         Bleu   
type_client                                                                dual   
libelle_naf                   Administration d'immeubles et autres biens imm...   
activite_nce                  Services marchands divers (hors santé et ensei...   
orientation_economique                                            Bassin Urbain   
urbanite_ruralite                                             Com > 200 m habts   
dynamique_demographique_bv                                         Grande Ville   
environnement_demographique           Bassin Urbain en croissance démographique   
seg_dyn_entre                                              Dynamique Economique   

                                freq  
produit                       307470  
type_d_offre                  321391  
type_de_prix                  192627  
canal_de_vente                234361  
zone                           30408  
marche_de_la_sc               301178  
segment_societe_contractante  283644  
entite_societe_contractante   121847  
profil_prm                    284314  
couleur_tarif_elec            300355  
type_client                   224594  
libelle_naf                   188267  
activite_nce                  268479  
orientation_economique        234123  
urbanite_ruralite             153560  
dynamique_demographique_bv    234123  
environnement_demographique   234123  
seg_dyn_entre                 264416

In [48]:
### Merging TRAIN AND TEST for pre-processing

In [49]:
df_train['Type'] = 'Train'

In [50]:
df_test['Type'] = 'Test'

In [51]:
fullData = pd.concat([df_train,df_test],axis=0) #Combined both Train and Test Data set

In [52]:
fullData.shape

(436440, 37)

In [53]:
# Treating missing values

In [54]:
fullData['type_de_prix'].fillna("Autre", inplace = True)

In [55]:
fullData['zone'].fillna("Autre", inplace = True)

In [56]:
fullData['profil_prm'].fillna("Autre", inplace = True)

In [57]:
fullData['couleur_tarif_elec'].fillna("Autre", inplace = True)

In [58]:
fullData['type_client'].fillna("Autre", inplace = True)

In [59]:
fullData['libelle_naf'].fillna("Autre", inplace = True)

In [60]:
fullData['activite_nce'].fillna("Autre", inplace = True)

In [61]:
fullData['orientation_economique'].fillna("Autre", inplace = True)

In [62]:
fullData['anciennete_client'].fillna(13.509, inplace = True)

In [63]:
fullData['prix_gaz_m3'].fillna(21.1924, inplace = True)

In [64]:
fullData['prix_elec_m3'].fillna(39.1193, inplace = True)

In [66]:
## Fill NAN with Mean of same 'profil_prm'
fullData["volume_annuel"].fillna(fullData.groupby("profil_prm")["volume_annuel"].transform("mean"), inplace=True)

In [68]:
### Convert string categorical variable into number category

number = LabelEncoder()

In [69]:
fullData['produit'] = number.fit_transform(fullData['produit'].astype('str'))

In [71]:
fullData['type_d_offre'] = number.fit_transform(fullData['type_d_offre'].astype('str'))

In [72]:
fullData['type_de_prix'] = number.fit_transform(fullData['type_de_prix'].astype('str'))

In [73]:
fullData['canal_de_vente'] = number.fit_transform(fullData['canal_de_vente'].astype('str'))

In [74]:
fullData['zone'] = number.fit_transform(fullData['zone'].astype('str'))

In [76]:
fullData['marche_de_la_sc'] = number.fit_transform(fullData['marche_de_la_sc'].astype('str'))

In [78]:
fullData['segment_societe_contractante'] = number.fit_transform(fullData['segment_societe_contractante'].astype('str'))

In [79]:
fullData['entite_societe_contractante'] = number.fit_transform(fullData['entite_societe_contractante'].astype('str'))

In [80]:
fullData['profil_prm'] = number.fit_transform(fullData['profil_prm'].astype('str'))

In [81]:
fullData['couleur_tarif_elec'] = number.fit_transform(fullData['couleur_tarif_elec'].astype('str'))

In [82]:
fullData['type_client'] = number.fit_transform(fullData['type_client'].astype('str'))

In [83]:
fullData['libelle_naf'] = number.fit_transform(fullData['libelle_naf'].astype('str'))

In [84]:
fullData['activite_nce'] = number.fit_transform(fullData['activite_nce'].astype('str'))

In [86]:
fullData['orientation_economique'] = number.fit_transform(fullData['orientation_economique'].astype('str'))

In [85]:
fullData.head()

Type  activite_nce  anciennete_client  canal_de_vente  cible  \
0  Train            35          13.964384               0    1.0   
1  Train            35          13.964384               0    1.0   
2  Train            35          13.964384               0    1.0   
3  Train            35          13.964384               0    1.0   
4  Train            35          14.920548               0    1.0   

   couleur_tarif_elec  dep_moyenne_salaires_horaires  duree  \
0                   1                      11.173529     12   
1                   1                      11.173529     12   
2                   1                      11.173529     12   
3                   1                      11.173529     12   
4                   0                      11.981429     12   

                          dynamique_demographique_bv  echeance_annee  \
0                                       Grande Ville            2016   
1                                       Grande Ville            2014   
2                                       Grande Ville            2013   
3                                       Grande Ville            2015   
4  1.Accroissement par excédent naturel et migrat...            2014   

   echeance_mois  entite_societe_contractante  \
0              3                            2   
1              3                            2   
2              3                            2   
3              3                            2   
4              9                            2   

                     environnement_demographique  evolution_pop_percent  \
0      Bassin Urbain en croissance démographique                   0.07   
1      Bassin Urbain en croissance démographique                   0.07   
2      Bassin Urbain en croissance démographique                   0.07   
3      Bassin Urbain en croissance démographique                   0.07   
4  Bassin Industriel en croissance démographique                   0.06   

   libelle_naf  marche_de_la_sc  nb_atifs  nb_dem_12  nb_dem_reco_12  \
0           46                1    3642.0          0               0   
1           46                1    3642.0          0               0   
2           46                1    3642.0          0               0   
3           46                1    3642.0          0               0   
4          228                2     745.0          0               0   

   nb_logement  nb_proprietaire  nb_recla_12  nb_recla_reco_12  \
0       4574.0           1693.0            0                 0   
1       4574.0           1693.0            0                 0   
2       4574.0           1693.0            0                 0   
3       4574.0           1693.0            0                 0   
4        623.0            430.0            0                 0   

  orientation_economique  population  prix_elec_m3  prix_gaz_m3  produit  \
0          Bassin Urbain      9751.0     34.367000    16.415322        0   
1          Bassin Urbain      9751.0     43.686875    27.547958        0   
2          Bassin Urbain      9751.0     39.119300    21.192400        0   
3          Bassin Urbain      9751.0     40.846316    22.850872        0   
4      Bassin Industriel      1700.0     41.823333    24.530851        1   

   profil_prm         seg_dyn_entre  segment_societe_contractante  \
0           2  Dynamique Economique                             2   
1           2  Dynamique Economique                             2   
2           2  Dynamique Economique                             2   
3           2  Dynamique Economique                             2   
4          13  Dynamique Economique                             3   

   type_client  type_d_offre  type_de_prix  urbanite_ruralite  volume_annuel  \
0            1             0             2  Com > 200 m habts        0.11860   
1            1             0             2  Com > 200 m habts        0.11860   
2            1             0             2  Com > 200 m habts        0.11860   
3            1 

In [87]:
## Drop unwanted columns 

In [88]:
fullData.drop('echeance_annee', axis=1, inplace=True)

In [89]:
fullData.drop('population', axis=1, inplace=True)

In [90]:
fullData.drop('evolution_pop_percent', axis=1, inplace=True)

In [91]:
fullData.drop('nb_proprietaire', axis=1, inplace=True)

In [92]:
fullData.drop('nb_logement', axis=1, inplace=True)

In [93]:
fullData.drop('dep_moyenne_salaires_horaires', axis=1, inplace=True)

In [94]:
fullData.drop('urbanite_ruralite', axis=1, inplace=True)

In [95]:
fullData.drop('nb_atifs', axis=1, inplace=True)

In [96]:
fullData.drop('dynamique_demographique_bv', axis=1, inplace=True)

In [97]:
fullData.drop('environnement_demographique', axis=1, inplace=True)

In [98]:
fullData.drop('seg_dyn_entre', axis=1, inplace=True)

In [99]:
fullData.head()

Type  activite_nce  anciennete_client  canal_de_vente  cible  \
0  Train            35          13.964384               0    1.0   
1  Train            35          13.964384               0    1.0   
2  Train            35          13.964384               0    1.0   
3  Train            35          13.964384               0    1.0   
4  Train            35          14.920548               0    1.0   

   couleur_tarif_elec  duree  echeance_mois  entite_societe_contractante  \
0                   1     12              3                            2   
1                   1     12              3                            2   
2                   1     12              3                            2   
3                   1     12              3                            2   
4                   0     12              9                            2   

   libelle_naf  marche_de_la_sc  nb_dem_12  nb_dem_reco_12  nb_recla_12  \
0           46                1          0               0            0   
1           46                1          0               0            0   
2           46                1          0               0            0   
3           46                1          0               0            0   
4          228                2          0               0            0   

   nb_recla_reco_12  orientation_economique  prix_elec_m3  prix_gaz_m3  \
0                 0                       3     34.367000    16.415322   
1                 0                       3     43.686875    27.547958   
2                 0                       3     39.119300    21.192400   
3                 0                       3     40.846316    22.850872   
4                 0                       1     41.823333    24.530851   

   produit  profil_prm  segment_societe_contractante  type_client  \
0        0           2                             2            1   
1        0           2                             2            1   
2        0           2                             2            1   
3        0           2                             2            1   
4        1          13                             3            2   

   type_d_offre  type_de_prix  volume_annuel  zone  
0             0             2        0.11860     0  
1             0             2        0.11860     0  
2             0             2        0.11860     0  
3             0             2        0.11860     0  
4             1            14        5.50545     2

In [100]:
fullData.shape

(436440, 26)

In [101]:
## Seperating Train / Test again

In [102]:
train_df = fullData[fullData['Type']=='Train']

In [107]:
test_df = fullData[fullData['Type']=='Test']

In [115]:
train_df.shape

(356669, 25)

In [105]:
train_df.head()

Type  activite_nce  anciennete_client  canal_de_vente  cible  \
0  Train            35          13.964384               0    1.0   
1  Train            35          13.964384               0    1.0   
2  Train            35          13.964384               0    1.0   
3  Train            35          13.964384               0    1.0   
4  Train            35          14.920548               0    1.0   

   couleur_tarif_elec  duree  echeance_mois  entite_societe_contractante  \
0                   1     12              3                            2   
1                   1     12              3                            2   
2                   1     12              3                            2   
3                   1     12              3                            2   
4                   0     12              9                            2   

   libelle_naf  marche_de_la_sc  nb_dem_12  nb_dem_reco_12  nb_recla_12  \
0           46                1          0               0            0   
1           46                1          0               0            0   
2           46                1          0               0            0   
3           46                1          0               0            0   
4          228                2          0               0            0   

   nb_recla_reco_12  orientation_economique  prix_elec_m3  prix_gaz_m3  \
0                 0                       3     34.367000    16.415322   
1                 0                       3     43.686875    27.547958   
2                 0                       3     39.119300    21.192400   
3                 0                       3     40.846316    22.850872   
4                 0                       1     41.823333    24.530851   

   produit  profil_prm  segment_societe_contractante  type_client  \
0        0           2                             2            1   
1        0           2                             2            1   
2        0           2                             2            1   
3        0           2                             2            1   
4        1          13                             3            2   

   type_d_offre  type_de_prix  volume_annuel  zone  
0             0             2        0.11860     0  
1             0             2        0.11860     0  
2             0             2        0.11860     0  
3             0             2        0.11860     0  
4             1            14        5.50545     2

In [114]:
test_df.shape

(79771, 24)

In [111]:
test_df.head()

Type  activite_nce  anciennete_client  canal_de_vente  couleur_tarif_elec  \
0  Test            35          13.964384               0                   1   
1  Test             3          13.509000               1                   0   
2  Test             3          13.509000               1                   0   
3  Test             3          13.509000               1                   0   
4  Test            13          13.830137               0                   0   

   duree  echeance_mois  entite_societe_contractante  libelle_naf  \
0     12              3                            2           46   
1     36              6                            4           59   
2     36              1                            4           59   
3     12              8                            4           59   
4     12              8                            0          224   

   marche_de_la_sc  nb_dem_12  nb_dem_reco_12  nb_recla_12  nb_recla_reco_12  \
0                1          0               0            0                 0   
1                2          0               0            0                 0   
2                2          2               1            0                 0   
3                2          0               0            0                 0   
4                2          0               0            0                 0   

   orientation_economique  prix_elec_m3  prix_gaz_m3  produit  profil_prm  \
0                       3     38.065238    17.313520        0           2   
1                       3     34.830435    16.783495        1          15   
2                       3     41.947143    16.615879        1          15   
3                       3     35.679091    16.614452        1          13   
4                       3     35.679091    16.614452        1          15   

   segment_societe_contractante  type_client  type_d_offre  type_de_prix  \
0                             2            1             0             2   
1                             3            0             1            14   
2                             3            0             1            14   
3                             3            0             1             0   
4                             3            2             1             0   

   volume_annuel  zone  
0        0.11860     0  
1        4.96180     3  
2        4.96180     3  
3        1.28400     2  
4        3.78125     1

In [110]:
test_df.drop('cible', axis=1, inplace=True)

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [112]:
test_df.drop('Type', axis=1, inplace=True)

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [113]:
train_df.drop('Type', axis=1, inplace=True)

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [116]:
train_df.to_csv("train_preprocess_v1.csv", index = False)

In [117]:
test_df.to_csv("test_preprocess_v1.csv", index = False)